version: '3'

services:
  blog:
    container_name: hugo
    image: "peaceiris/hugo:v0.124.0"
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
      - --buildFuture