version: '3'

services:
  blog:
    container_name: hugo
    image: "peaceiris/hugo:v0.99.1"
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --buildDrafts
      - --buildFuture
  test-prod:
    image: "peaceiris/hugo:v0.99.1"
    volumes:
      - ${PWD}:/src
    command:
      - --minify